### PR TITLE
added update_attributes to base and #favorite? to saved_search

### PR DESCRIPTION
**Pull request by ryanhertz**
@bhornseth

### CODE REVIEW

**Comment by bhornseth** [comment]
cc @mjobrien 

@ryanhertz and I talked about this a bit last week, and I thought this approach was alright. I'm a bit swamped at the moment, so I might not get thru this today

**Comment by baron-hines** [comment]
So this is a public method that lets us update private class attributes? I'm curious why we would want this rather than having the models set their attributes so you can write to them. Especially since some attributes can be 'computed' and this allows you to sidestep any logic that a model may want you to use.

**Comment by GutsyGusty** [comment]
I agree with @baron-hines. Perhaps you want to use `public_send` to prevent setting private attributes.

**Comment by ryanhertz** [comment]
I'm using this to do mass assignment in an update action where I don't know what attributes are being updated. I think `public_send` would work for me.

**Comment by baron-hines** [comment]
Awesome, if you can use `public_send` I'm :+1:

**Pull request merged**
