### PR TITLE
MWEB-1217: handle empty arrays from default service

### PR DESCRIPTION
**Pull request by ryanhertz**
@sparkapi/owners @highplainsscripter @bhornseth It's possible for the idx links default service to return an empty array when there is no default. The Defaultable module is using the find method from Finders and using an "id" of "default". We end up with the correct api path even though default isn't really an id. Usually when we make an api request that includes an id and there is nothing there, we get a 404 from the api and a SparkApi::NotFound is raised. In this case, we get a 200 and an empty array. Since the api request completed successfully, `Finders#find_single` attempts to create a new instance from the response and fails. I've only noticed this problem when using Defaultable, but I decided to put the fix in Finders because I think it's generally reasonable to check that the response is not nil before trying to create an instance.

### CODE REVIEW

**Comment by bhornseth** [comment]
I wonder if we shouldn't trigger a `NotFound` exception to stay consistent with the other `find` behavior. I guess that itself could be considered a departure since the `NotFound` exceptions are really proxied 404s from the API :confused: 

Does everything else that calls `find` with an Id either return a model or result in a NotFound exception? If it does, I think that should guide how we handle this case, if not I'm alright with this.

> I decided to put the fix in Finders because I think it's generally reasonable to check that the response is not nil before trying to create an instance.

:+1: to this approach

**Comment by mjobrien** [comment]
It seems hard to determine the most consistent approach here, when by my reading, the API itself is not consistent.

How are `NotFound` exceptions handled in our applications? If throwing `NotFound` exceptions is going to require a lot of extra `rescue` calls to handle the API returning an empty set, that may sway the decision.

> Does everything else that calls find with an Id either return a model or result in a NotFound exception? If it does, I think that should guide how we handle this case, if not I'm alright with this.

I agree with this. And my intuition tells me that it won't be necessary to `rescue` a large number of `NotFound` exceptions. But you guys are the ones working in that code every day.

**Comment by ryanhertz** [comment]
As far as I know, any time `find` is called with an id, a model is returned or a `NotFound` is raised. The problem is that "default" isn't an id. When you do `IdxLink.find('default')`, the api service that is used is `/idxlinks/default`, but it's just a coincidence that it is in the same format as the `/idxlinks/<id>` service. The alternative would be to change `Defaultable#default` and `Defaultable#find` so that they didn't use `Finders#find`.

**Comment by bhornseth** [comment]
> How are NotFound exceptions handled in our applications?

They're basically rescued where they need to be (e.g. where we expect the possibility of 404s), but there aren't many of those places. Usually if we're searching by Id, it's expected that the record matching that Id is there and accessible.

I'd say we should aim for consistency of client experience and raise an exception in this case over returning null. 

Or, option 2: would it make more sense to have a 'default' class method for `IdxLink`? that'd allow us to address the API inconsistency in the one model, and at least keep it confined to some extent. Maybe that doesn't jive with the usage though

**Pull request closed without merging**
