### PR TITLE
Updated to faraday 0.9.0

### PR DESCRIPTION
**Pull request by dgmyrek**
Pretty simple change to make the client compatible with the new register_middleware format and fix a couple tests to validate against a new SSLOptions struct.

### CODE REVIEW

**Comment by bhornseth** [comment]
This looks good to me. Maybe someone from @sparkapi/webdev can chime in as well, but I see no reason not to get this merged.

**Comment by baron-hines** [comment]
Looks fine to me.

**Comment by mjobrien** [comment]
Code looks good; I'll merge.

From a procedural perspective, including the reason why a dependency is being changed in the commit message seems helpful, especially since there's no changelog. Also, I'm curious if this will go out as a patch version or minor version bump.

**Comment by bhornseth** [comment]
Looking at the [faraday 0.9.0 changelog](https://github.com/lostisland/faraday/blob/master/CHANGELOG.md), I think we'd be safe using a patch version. Thoughts?

Once we decide, I'll throw in a changelog file and we can cut a new gem.

**Comment by mjobrien** [comment]
I agree that a patch version is safe.

I don't think we're doing full-on SemVer, but fwiw, SemVer says dependency changes without public API changes are patch or minor depending on whether the change is due to a bugfix or a new feature.

**Comment by dgmyrek** [comment]
@mjobrien, I'll note that commit message procedure for next time. For documentation's sake the change was initiated so we can integrate this gem with the google API client gem that's dependent on faraday >= 0.9.0.

**Comment by wlmcewen** [comment]
Nice work, @dgmyrek.

**Pull request merged**
